name: ABP CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Kk*123456" # fix cứng để CI chạy
        ports:
          - 1433:1433
        # bỏ healthcheck vì image không có sẵn sqlcmd

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server to start..."
          for i in {1..30}; do
            (echo > /dev/tcp/localhost/1433) >/dev/null 2>&1 && echo "SQL Server is up!" && break
            echo "SQL not ready yet..."
            sleep 2
          done

      # Nếu bạn muốn apply migration khi CI chạy thì bật bước này
      # - name: Run EF Core migrations
      #   run: dotnet ef database update -p ABP_TopCv.EntityFrameworkCore -s ABP_TopCv.HttpApi.Host

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run Application.Tests
        run: dotnet test ./test/ABP_TopCv.Application.Tests/ABP_TopCv.Application.Tests.csproj --no-build --verbosity normal

      - name: Run Domain.Tests
        run: dotnet test ./test/ABP_TopCv.Domain.Tests/ABP_TopCv.Domain.Tests.csproj --no-build --verbosity normal

      - name: Run EntityFrameworkCore.Tests
        run: dotnet test ./test/ABP_TopCv.EntityFrameworkCore.Tests/ABP_TopCv.EntityFrameworkCore.Tests.csproj --no-build --verbosity normal


  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/abp-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/abp-app:latest
